# Generated by Django 4.2.8 on 2024-05-23 04:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_product_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="zip",
            field=models.CharField(default="-", max_length=255),
        ),
    ]
